Implement persistent, encrypted storage instead of using /nvram Integrate application image as signed squashfs filesystem.

diff --git a/atom/mod/etc/init.d/S91-ffinit b/atom/mod/etc/init.d/S91-ffinit
--- a/atom/mod/etc/init.d/S91-ffinit
+++ b/atom/mod/etc/init.d/S91-ffinit
@@ -8,67 +8,132 @@
 #	- transferring roots .ssh from persistent memory
 #	
 #
-echo `date` :: ffinit
 
 export FFINSTDIR=/usr/local
 export FFRITZ_HOME=/var/media/ftp/ffritz
 export FFLOG=/var/log/ffritz.log
-PATH=$PATH:$FFINSTDIR/bin
 
+DATADIR=$FFRITZ_HOME/data
+
+NVRAM_FILE=$DATADIR/ffstore.dat
+BINFILE=$DATADIR/ffimage.bin
+PRIVKEY=/var/flash/websrv_ssl_key.pem
+
+NVRAM_COPY=/var/tmp/ffnvram
+
+echo `date` :: ffinit >>$FFLOG
+
+## Temporarily start telnetd
+##
+/usr/bin/telnetd -l /sbin/ar7login
+nohup sh -c "sleep 300; echo killing telnetd > /dev/console; sleep 10; killall telnetd" &
+
+## Decrypt presistent storage image to /var/tmp/ffnvram
+##
+## Exit code: 0 on success, 1 otherwise
+##
+decrypt_nvram()
+{
+## look for encrypted storage
+	if [ ! -r $NVRAM_FILE ]; then
+		echo encrypted storage $NVRAM_FILE not present >>$FFLOG
+		return 1
+	fi
+
+### if found, try to decrypt it into ramfs
+	privatekeypassword | openssl enc -d -pass stdin -aes-256-cbc -in $NVRAM_FILE -out $NVRAM_COPY/nv.tar
+
+	if [ $? -ne 0 ]; then
+		echo failed to decypt $NVRAM_FILE >>$FFLOG
+		return 1
+	fi
+
+### unpack it to ramfs
+	cd $NVRAM_COPY	|| exit 1
+	tar xf $NVRAM_COPY/nv.tar || exit 1
+	rm -f $NVRAM_COPY/nv.tar
+	chmod 700 $NVRAM_COPY
+}
+
+#####################################
+
+## Make users
+grep ffritz /etc/passwd >/dev/null || echo ffritz:x:8000:8000:ffritz:/var/media/ftp/ffritz:/bin/sh >> /etc/passwd
+grep ffritz /etc/group >/dev/null  || echo ffritz:x:8000: >> /etc/group
+grep usb /etc/group >/dev/null     || echo usb:x:8001:ffritz >> /etc/group
+
+# The upmpdcli user is required by the upmpdcli daemon
+#
+grep upmpdcli /etc/passwd >/dev/null || echo upmpdcli:x:8001:8000:upmpdcli:/var/media/ftp/ffritz:/bin/sh >> /etc/passwd
+
+if [ ! -d ~ffritz/.mpd ]; then
+    mkdir -p ~ffritz/.mpd
+fi
+if [ ! -d ~ffritz/etc ]; then
+    mkdir -p ~ffritz/etc
+fi
+
+chown ffritz:ffritz ~ffritz
+chown ffritz:ffritz ~ffritz/.mpd
+chown ffritz:ffritz ~ffritz/etc
+chmod 775 ~ffritz
+chmod 775 ~ffritz/.mpd
+chmod 775 ~ffritz/etc
+
+## begin log
 touch $FFLOG
 chmod 666 $FFLOG
 
-CP="$FFINSTDIR/bin/rpc_cp"
+## Make a RAM copy that contains the contents of the encrypted storage
+rm -rf $NVRAM_COPY
+mkdir -p $NVRAM_COPY  || exit 1
+chmod 700 $NVRAM_COPY || exit 1
 
-$FFINSTDIR/etc/mkusers
+touch /var/tmp/openssl.cnf
 
-## Transfer required nvram stuff from arm
-#
-rpc tar cf - nvram/shadow nvram/root-ssh_x86 nvram/dropbear_x86 | (cd /var/tmp; tar xf -)
+decrypt_nvram
 
-mv /var/tmp/nvram/shadow /var/tmp/shadow
+## If something went wrong with decrypting nvram storage, try legacy mode
+## (copy from /nvram on ARM)
+if [ $? -ne 0 ]; then
+	echo failed to decrypt nvram image, copying /nvram data >>$FFLOG
+	rpc tar cf - nvram/shadow nvram/root-ssh_x86 nvram/dropbear_x86 | (cd $NVRAM_COPY; tar xf -)
+	mv $NVRAM_COPY/nvram/shadow $NVRAM_COPY
+	mv $NVRAM_COPY/nvram/root-ssh_x86 $NVRAM_COPY/root-ssh
+	mv $NVRAM_COPY/nvram/dropbear_x86 $NVRAM_COPY/dropbear
+	rmdir $NVRAM_COPY/nvram
+fi
 
-## Create dummy shadow entry for ffritz so that it's possible to 
-# assign a login
-#
-grep ffritz /etc/shadow >/dev/null  || echo ffritz:x:1:0:99999:7::: >> /etc/shadow
+## install data to correct places
+if [ -r $NVRAM_COPY/shadow ]; then
+	rm -f /var/tmp/shadow
+	ln -s $NVRAM_COPY/shadow /var/tmp/shadow
+fi
 
-## transfer dropbear data from nvram
-#
 rm -rf /var/tmp/dropbear
+mkdir -p $NVRAM_COPY/dropbear
+chmod 700 $NVRAM_COPY/dropbear
+ln -s $NVRAM_COPY/dropbear /var/tmp/dropbear
 
-if [ -d /var/tmp/nvram/dropbear_x86 ]; then
-	mv /var/tmp/nvram/dropbear_x86 /var/tmp/dropbear
-else
-	rpc mkdir /nvram/dropbear_x86 && rpc chmod 700 /nvram/dropbear_x86
-	mkdir /var/tmp/dropbear
-	chmod 700 /var/tmp/dropbear
-fi
-
-# check for presence of keys. If required, create them.
-#
-for key in rsa dss ecdsa; do
-	if [ ! -f /var/tmp/dropbear/dropbear_${key}_host_key ]; then
-		echo creating /var/tmp/dropbear/dropbear_${key}_host_key >> $FFLOG
-		$FFINSTDIR/bin/dropbearkey -t $key -f /var/tmp/dropbear/dropbear_${key}_host_key > /var/tmp/dropbear/id_${key}.pub || echo dropbearkey failed >> $FFLOG
-		rpc sh $CP /var/tmp/dropbear/dropbear_${key}_host_key /var/tmp/dropbear/id_${key}.pub /nvram/dropbear_x86
-	fi
-done
-
-# copy roots ssh stuff
-#
 rm -rf /var/tmp/root-ssh
-if [ -d /var/tmp/nvram/root-ssh_x86 ]; then
-	mv /var/tmp/nvram/root-ssh_x86 /var/tmp/root-ssh
-else
-	mkdir -p /var/tmp/root-ssh
-	chmod 700 /var/tmp/root-ssh
-	rpc mkdir /nvram/root-ssh_x86 && rpc chmod 700 /nvram/root-ssh_x86
+mkdir -p $NVRAM_COPY/root-ssh
+chmod 700 $NVRAM_COPY/root-ssh
+ln -s $NVRAM_COPY/root-ssh /var/tmp/root-ssh
+
+## create dropbear RSA private key
+## This is supposed to work even if all of the above failed to be able to start
+## a dropbear daemon. The final fallback is the temporary telnet daemon ..
+##
+if [ ! -f /var/tmp/dropbear/dropbear_rsa_host_key.cvt -o ! -f /var/tmp/dropbear/rsa_key_dontoverwrite ]; then
+	privatekeypassword | openssl rsa -passin stdin -in $PRIVKEY -out /tmp/websrv_ssl_key_dec.pem && \
+		dropbearconvert openssh dropbear /tmp/websrv_ssl_key_dec.pem /var/tmp/dropbear/dropbear_rsa_host_key.cvt
+	rm -f /tmp/websrv_ssl_key_dec.pem
+
+	## install as private rsa key. If this fails, dropbear will either use an existing one from 
+	## /nvram or fail to start. We dont want to use random host keys for each startup.
+	if [ -r /var/tmp/dropbear/dropbear_rsa_host_key.cvt ]; then
+		mv /var/tmp/dropbear/dropbear_rsa_host_key.cvt /var/tmp/dropbear/dropbear_rsa_host_key
+	else
+		echo failed to convert box private key to dropbear private key >>$FFLOG
+	fi
 fi
-
-mkdir -p /var/run/mpd
-chown ffritz /var/run/mpd
-
-# A log rotator
-#
-$FFINSTDIR/bin/ffdaemon -i 1200 $FFINSTDIR/etc/fflogrotate 
