Squashed commit of 6591-devel
    Add -f to ffdaemon
    Provide wireguard for 7.21
    pihole fixes
    - Add to core image V28
    - libmultid: also change DHCPv6 port
    - pihole start/stop scripts
    - change pihole build
    Added socat, libmultid to base package
    Add -s to nvsync
    Add some sha files
    Switch 4.1.199 to avm kernel
    libmutdid: add missing ipv6
    Add dialog, ALSA doc
    Remove busybox from base image, add bb telnetd link in /usr/sbin
    S93-image: abort if already mounted
    buildroot with sdk build fix
    atom base tools rework
    System tools (ffinstall, ffstop, ffstart) enhanced
    ffservice: classify daemon failures as BAD, set return code for status
    Add ffshutdown/restart binaries
    Merge alsa branch
    ffdaemon: handle stale pid files when killing
    pihole: Run pihole-localhost service (LOCALHOST_UPDATE_INTERVAL option)
    shairport: change startup delay
    Makefile rework, separate toolchain build for 2020-02
    Refactoring
    - Binary ffwrap and infrastructure
    - Move fftools to common (ffwrap, ffdaemon)
    - usbplayd: Move in libmaru binaries, purge libmaru
    - Buildroot:
     - Start buildroot 2020-08
     - Split toolchain build

diff --git a/atom/mod/usr/bin/nvsync b/atom/mod/usr/bin/nvsync
--- a/atom/mod/usr/bin/nvsync
+++ b/atom/mod/usr/bin/nvsync
@@ -27,10 +27,16 @@ NVRAM_FLASH=/nvram/ffnvram
 KEY_ENC=$DATADIR/key.enc
 KEY_PLAIN=/tmp/key.bin
 
+ECHO=echo
+if [ "$1" = "-s" ]; then
+	ECHO=
+	shift
+fi
+
 ## See 6591 comment above
 #
 if [ -d $NVRAM_FLASH -a "`readlink -f $NVRAM_COPY`" = "`readlink -f $NVRAM_FLASH`" ]; then
-	echo +++ Success
+	$ECHO +++ Success
 	exit 0
 fi
 
@@ -66,7 +72,7 @@ rm -f /tmp/ffstore.tar
 rm -f $KEY_PLAIN
 
 if [ $rc -ne 0 ]; then
-	echo +++ FAILED
+	echo '*** FAILED' 1>&2
 	exit 1
 fi
 
@@ -74,4 +80,4 @@ fi
 chmod 700 /tmp/ffstore.dat
 mv /tmp/ffstore.dat $NVRAM_FILE || exit 1
 
-echo +++ Success
+$ECHO +++ Success
